from typing import Tuple

import numpy as np
from ase import Atoms
from phonopy import Phonopy
from phonopy.structure.atoms import PhonopyAtoms


def structure_calculate_phonons(
    atoms: Atoms,
    displacement: float,
    supercell: Tuple[int, int, int],
    qpoint_mesh: Tuple[int, int, int],
) -> Phonopy:
    """Compute phonon properties for an atomic structure via finite displacements.

    Builds a Phonopy supercell, applies small displacements, evaluates forces
    with the calculator attached to *atoms*, and derives force constants and
    the phonon mesh.

    Args:
        atoms: Structure to analyse.  Must have a calculator attached.
        displacement: Finite-displacement distance in Ångström.
        supercell: Diagonal supercell expansion, e.g. ``(4, 4, 4)`` for bulk
            or ``(4, 4, 1)`` for a 2-D slab.
        qpoint_mesh: Monkhorst–Pack mesh for the phonon DOS / stability
            check, e.g. ``(20, 20, 20)``.
    Returns:
        A :class:`~phonopy.Phonopy` object with force constants, symmetrised
        force constants, and a completed mesh calculation.

    Raises:
        RuntimeError: If no calculator is set or Phonopy fails to generate
            displaced supercells.
    """
    if atoms.calc is None:
        raise RuntimeError("No calculator set for the structure.")

    phnpy_structure = PhonopyAtoms(
            symbols=atoms.get_chemical_symbols(),
            positions=atoms.get_positions(),
            cell=atoms.get_cell().array,
        )

    phonons = Phonopy(
            phnpy_structure,
            supercell_matrix=np.diag(supercell),
            primitive_matrix="auto",
        )

    phonons.generate_displacements(distance=displacement)

    sets_of_forces = []
    supercells = phonons.supercells_with_displacements

    if supercells is None:
        raise RuntimeError("Distorted cells were not generated by Phonopy.")

    from rapmat.calculators import cleanup_calculator_files
    
    cleanup_calculator_files(atoms.calc)

    for phonopy_cell in supercells:
        cleanup_calculator_files(atoms.calc)
        
        ase_cell = Atoms(
            symbols=phonopy_cell.symbols,
            positions=phonopy_cell.positions,
            cell=phonopy_cell.cell,
            pbc=True,
        )

        ase_cell.calc = atoms.calc

        forces = ase_cell.get_forces()
        sets_of_forces.append(forces)

    phonons.forces = np.array(sets_of_forces)
    phonons.produce_force_constants()
    phonons.symmetrize_force_constants()
    phonons.run_mesh(qpoint_mesh)

    return phonons


def get_mesh_min_frequency(phonons: Phonopy) -> float:
    """Return the minimum phonon frequency from the mesh (THz).

    Args:
        phonons: A :class:`~phonopy.Phonopy` object that has already had
            :meth:`run_mesh` called.

    Returns:
        The minimum frequency in THz. Values below zero indicate imaginary modes.
    """
    return float(np.min(phonons.get_mesh_dict()["frequencies"]))


def structure_has_imag_phonon_freq(phonons: Phonopy, threshold: float = -1e-3) -> bool:
    """Check whether a phonon spectrum contains imaginary frequencies.

    Args:
        phonons: A :class:`~phonopy.Phonopy` object that has already had
            :meth:`run_mesh` called.
        threshold: Frequency cutoff in THz.  Any frequency below this
            value is considered imaginary.  Default is ``-1e-3``.

    Returns:
        ``True`` if at least one frequency falls below *threshold*.
    """
    return get_mesh_min_frequency(phonons) < threshold
