import numpy as np

from ase import Atoms
from typing import Tuple
from phonopy import Phonopy
from phonopy.structure.atoms import PhonopyAtoms


def structure_calculate_phonons(
    atoms: Atoms,
    displacement: float,
    supercell: Tuple[int, int, int],
    qpoint_mesh: Tuple[int, int, int],
    progress_callback=None,
) -> Phonopy:
    if atoms.calc is None:
        raise RuntimeError("No calculator set for the structure.")

    phnpy_structure = PhonopyAtoms(
        symbols=atoms.get_chemical_symbols(),
        positions=atoms.get_positions(),
        cell=atoms.get_cell().array,
    )

    phonons = Phonopy(
        phnpy_structure,
        supercell_matrix=np.diag(supercell),
        primitive_matrix="auto",
    )

    phonons.generate_displacements(distance=displacement)

    sets_of_forces = []
    supercells = phonons.supercells_with_displacements

    if supercells is None:
        raise RuntimeError("Distorted cells were not generated by Phonopy.")

    from rapmat.calculators import cleanup_calculator_files

    cleanup_calculator_files(atoms.calc)

    counter = 0
    for phonopy_cell in supercells:
        counter += 1
        if progress_callback:
            progress_callback(
                0, 0, f"Processing deformed structure {counter}/{len(supercells)}"
            )

        cleanup_calculator_files(atoms.calc)

        ase_cell = Atoms(
            symbols=phonopy_cell.symbols,
            positions=phonopy_cell.positions,
            cell=phonopy_cell.cell,
            pbc=True,
        )

        ase_cell.calc = atoms.calc

        forces = ase_cell.get_forces()
        sets_of_forces.append(forces)

    phonons.forces = np.array(sets_of_forces)
    phonons.produce_force_constants()
    phonons.symmetrize_force_constants()
    phonons.run_mesh(qpoint_mesh)

    return phonons


def get_mesh_min_frequency(phonons: Phonopy) -> float:
    return float(np.min(phonons.get_mesh_dict()["frequencies"]))


def structure_has_imag_phonon_freq(phonons: Phonopy, threshold: float = -1e-3) -> bool:
    return get_mesh_min_frequency(phonons) < threshold
